### ISSUE TITLE
Questions about inference checkpoint and training code

### ISSUE THREAD

**Issue by XiaoKangW** [Style3D/FashionR2R#1]
First of all, I would like to express my sincere appreciation for your open-source work and the contribution it makes to the community.

It seems that you don't have a release checkpoint and in the wild datasets that can be used for inference to test the effect. In addition, I would like to ask if the training code can be released? Or which scripts based on diffuser can reproduce your training code?

Thank you for your time and assistance.

Best regards

**Comment by Style3D** [comment]
Thank you for your interest in our work. We have released the SynFashion dataset, which is available on the project page. If by "in the wild datasets" you are referring to Face Synthetics, you can find it in their [repo](https://github.com/microsoft/FaceSynthetics). Please note that the checkpoints and training code are still being prepared and may not be made available due to commercial and legal considerations.

**Comment by PBR3DGen** [comment]
Thank you very much for your reply. I am currently meeting two issues while trying to reproduce the process and would appreciate your advice:

- Do the real and synthetic data need to be of the same type?
- During inference for realistic images, should I use empty source and target prompts as in the example code you provided, or is there a need to fill in other prompts?

I would greatly appreciate it if you could help.

**Comment by XiaoKangW** [comment]
Thank you very much for your reply. I am currently meeting two issues while trying to reproduce the process and would appreciate your advice:

-Do the real and synthetic data need to be of the same type?
-During inference for realistic images, should I use empty source and target prompts as in the example code you provided, or is there a need to fill in other prompts?

I would greatly appreciate it if you could help.
